spring:
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "root"
        password: "123456"
        listener:
            simple:
                prefetch: 4
                concurrency: 4