version: '3'

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq-basic"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - TZ="Asia/Shanghai"
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/rabbitmq_data:/var/lib/rabbitmq
    entrypoint: rabbitmq-server